import type { Metadata } from "next";
import localFont from "next/font/local";
import SiteHeader from "../app/site-header";
import SiteFooter from "../app/site-footer";
import "./globals.css";

const roobert = localFont({
    src: [
        { path: "../public/fonts/roobert-regular.woff2", weight: "400" },
        { path: "../public/fonts/roobert-medium.woff2", weight: "500" },
        { path: "../public/fonts/roobert-semibold.woff2", weight: "600" },
        { path: "../public/fonts/roobert-bold.woff2", weight: "700" },
    ],
    variable: "--font-roobert",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Skinstric AI",
    description: "Generated by MSH",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${roobert.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <SiteHeader />
                {children}
                <SiteFooter />
            </body>
        </html>
    );
}
